#<% require 'kitchen-sync' %>
#<% time = Time.new.strftime("%F %H:%M") %>
---
driver:
  name: vagrant
   
provisioner:
  name: chef_zero
  environments_path: environments
  roles_path: roles
  data_bags_path: test/fixtures/data_bags

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[w_common]
    provisioner:
      client_rb:
        environment: testkitchen

suites:
  - name: test_w_common
    run_list:
      - role[w_common_role]
  - name: test_w_varnish
    driver:
      network:
        - ["private_network", {ip: "172.31.2.12"}]
    run_list:
      - role[w_common_role]
      - role[w_varnish_role]
    provisioner:
      data_bags_path: data_bags
  - name: test_w_apache
    driver:
      network:
        - ["private_network", {ip: "172.31.3.12"}]
    run_list:
      - role[w_common_role]
      - role[w_apache_role]
  - name: test_w_memcached
    driver:
      network:
        - ["private_network", {ip: "172.31.4.12"}]
    run_list:
      - role[w_common_role]
      - role[w_memcached_role]
  - name: test_w_mysql
    run_list:
      - role[w_common_role]
      - role[w_mysql_role]
  - name: test_w_percona
    driver:
      network:
        - ["private_network", {ip: "172.31.6.12"}]
    run_list:
      - role[w_common_role]
      - role[w_percona_role]
