language: ruby
rvm:
  - 2.2.2
  - 2.1.6
  - 2.0.0
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -q virtualbox --fix-missing
  - sudo wget -nv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
  - sudo dpkg -i vagrant_1.7.2_x86_64.deb
cache: bundler
sudo: required
env:
  matrix:
    - CHEF_VERSION=12.1.2 TK_INSTANCE=test-w-percona-ubuntu-1204
    - CHEF_VERSION=12.2.1 TK_INSTANCE=test-w-percona-ubuntu-1204
    - CHEF_VERSION=12.3.0 TK_INSTANCE=test-w-percona-ubuntu-1204
before_script:
  - "gem install bundler-audit --no-rdoc --no-ri && bundle-audit update"
script:
  - bundle-audit check
  - bundle exec rake foodcritic
  - bundle exec rake chefspec
  - bundle exec rake kitchen:$TK_INSTANCE